[theme]
base                      = "light"
backgroundColor           = "#f4f6fa"
secondaryBackgroundColor  = "#ffffff"
textColor                 = "#111827"
primaryColor              = "#00c896"
font                      = "sans serif"
